# Generated by Django 3.2.7 on 2022-04-20 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_orders_pickup_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Price',
            new_name='Total_Price',
        ),
    ]
