# Generated by Django 3.2.7 on 2022-04-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_rename_price_orders_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Weight',
            field=models.IntegerField(default=0),
        ),
    ]
