# Generated by Django 3.2.7 on 2022-04-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_alter_orders_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Total_Price',
            field=models.FloatField(),
        ),
    ]
