# Generated by Django 3.2.7 on 2022-05-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_alter_orders_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Total_Price',
            field=models.IntegerField(default=0),
        ),
    ]
